
language: node_js
sudo: required

notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - node


install:
  - npm install --production

script:
  - npm start

after_success:
  - chmod +x ./.travis/restart.sh
  - ./.travis/restart.sh

after_failure:
  - chmod +x ./.travis/restart.sh
  - ./.travis/restart.sh
